[build]
  publish = "dist"
  command = "bundle exec jekyll build --config jekyll.yml"
  environment = { JEKYLL_ENV = "development", BUNDLE_WITHOUT = "development", NODE_OPTIONS = "--max_old_space_size=8192" }

[context.production.environment]
  JEKYLL_ENV = "production"

[context.deploy-preview.environment]
  JEKYLL_ENV = "preview"

[dev]
  autoLaunch = false
  targetPort = 4000

[[redirects]]
from = "/vite-dev/*"
to = "http://localhost:3036/vite-dev/:splat"
force = true
status = 301

[[redirects]]
  from = "/fixtures/*"
  to = "/spec/fixtures/:splat"
  status = 200

[[headers]]
  for = "/fixtures/*"
  [headers.values]
    Cache-Control = "no-cache"
